"use strict";

exports.abacast      = require("./abacast");
exports.accujazz     = require("./accujazz");
exports.accuradio    = require("./accuradio");
exports.amazon       = require("./amazon");
exports.bandcamp     = require("./bandcamp");
exports.beats        = require("./beats");
exports.earbits      = require("./earbits");
exports.focusatwill  = require("./focusatwill");
exports.google       = require("./google");
exports.hoopla       = require("./hoopla");
exports.jango        = require("./jango");
exports.pandora      = require("./pandora");
exports.playerfm     = require("./playerfm");
exports.plugdj       = require("./plugdj");
exports.rhapsody     = require("./rhapsody");
exports.somafm       = require("./somafm");
exports.songza       = require("./songza");
exports.soundcloud   = require("./soundcloud");
exports.thedrop      = require("./thedrop");
exports.thisismyjam  = require("./thisismyjam");
exports.tidal        = require("./tidal");
exports.vk           = require("./vk");
exports.wonderfm     = require("./wonderfm");
exports.youtube      = require("./youtube");
